export {default as AuthAxios} from './axios/Auth'
export {default as ManagerAxios} from './axios/manager'
export {default as FileAxios} from './axios/files'
export {default as IconAxios} from './axios/icons'
export {default as ImagesAxios} from './axios/images'
export * from './store'
