export {default as addNewFunnel} from './AddFunnel'
export {default as getMyFiles} from './GetFiles'
export {default as getRandomIcons} from './GetIcons'
export * from './GetMyFunnels'
export * from './GetRandomImages'
export * from './GetSingleFunnel'
export * from './GetSinglePage'
export * from './Login'
export * from './SearchIcons'
export * from './SearchImages'
export * from './SubmitOptinForm'
export * from './AddPage'
export * from './EditPage'
