export {default as Container} from './Container'
export {default as Button} from './Button'
export {default as Text} from './Text'
export {default as Image} from './Image'
export {default as Resizer} from './Resizer'
export {default as Video} from './Video'
export {default as HyperLink} from './Hyperlink'
export {default as Divider} from './Divider'
export {default as Icon} from './Icons'
export {default as OptinForm} from './Form'
export {Quizz, QuizContainer, TextContainer} from './Quizz'
export {default as QuizzElement} from './Quizz/QuizzElement/QuizzElement'
export {default as Paragraph} from './Paraphraph'
export {default as HeaderComponent} from './Header/index'
export {default as FooterComponent, IconsContainer} from './Footer/index'
export {default as InputComponent} from './Form/InputComonent'
